version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - chat_db_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"

    ports:
      - "${POSTGRES_PORT}:5432"

    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "admin"]
      interval: 20s
      timeout: 20s
      retries: 5

  minio:
    image: quay.io/minio/minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    command: server --console-address ":9001" /data


  backend:
    # tag in pipeline should be same as in .env files
    image: "zzzzeonnnnn/${IMAGE_TAG}"
    build: .
    ports:
      - "${HOST_PORT}:8080"
    environment:
      PG_HOST: db
      PG_DB: chat_db
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"

      KEY_STORE_PASSWORD: "${KEY_STORE_PASSWORD}"
      KEY_PASSWORD: "${KEY_PASSWORD}"

      MINIO_HOST: minio
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
      MINIO_BUCKET: "${MINIO_BUCKET}"

    depends_on:
      db:
        condition: service_healthy


volumes:
  chat_db_vol: