version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - chat_db_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password

    ports:
      - "5432:5432"

    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "admin"]
      interval: 20s
      timeout: 20s
      retries: 5


  backend:
    image: zzzzeonnnnn/chat_backend:1
    build: .
    ports:
      - "8080:8080"
    environment:
      PG_HOST: db
      PG_DB: chat_db
      PG_USER: chat_user
      PG_PASSWORD: chat_password

    depends_on:
      db:
        condition: service_healthy

volumes:
  chat_db_vol: