spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demochat
    username: zeon
    password: 5837
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    database-platform:

  flyway:
    baseline-on-migrate: true