CREATE SEQUENCE IF NOT EXISTS chat_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS message_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS user_sequence START WITH 1 INCREMENT BY 1;