name: backend dev ci cd pipeline

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

env:
  # tag should be the same as in .env.dev file
  DOCKER_IMAGE_TAG: zzzzeonnnnn/chat_backend:dev-2.2
  HOST_FOLDER: /app/dev/

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests with Maven
        run: mvn --batch-mode --update-snapshots test

  docker-image:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker-image

    steps:
      - uses: actions/checkout@v3
      - uses: amplium/git-crypt-action@master
        with:
          key_encoded: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Send .env.dev & docker-compose.yml file to the virtual machine
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: ".env.dev, docker-compose.yml"
          target: /app/dev/

      - name: Start backend service
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /app/dev/ && mv .env.dev .env && docker compose down && docker compose pull && docker compose up -d
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
